### ISSUE TITLE
关于wiki中提供的Dockerfile

### ISSUE THREAD

**Issue by XiLingHost** [Suwings/MCSManager#63]
里面关于openjdk8的部分似乎在使用node:latest作为基础镜像的时候会出错
现在提供一份可用的Dockerfile

```
FROM node:latest
RUN apt-get update && apt-get install openjdk-8-jdk -y
WORKDIR /opt
RUN git clone https://github.com/Suwings/MCSManager.git
WORKDIR /opt/MCSManager
RUN npm install --production
EXPOSE 23333
CMD npm start
```

另外建议使用docker-compose进行部署，我也写了一个可用的docker-compose.yml

```
version: "3"
services:

 app:
  image: mcsmanager
  volumes:
   - ./server:/opt/MCSManager/server
   - ./users:/opt/MCSManager/users
  ports:
   - "86:23333"
   - "25565:25565"
   - "25566:25566"
  restart: always
  privileged: true
```

这个docker-compose.yml在部署前需要先在本地build上面的Dockerfile，tag为mcsmanager:latest，其中latest可省略
